export { admin } from './adminRoutes'
export { manager } from './managerRoutes'
export { deliveryManager } from './deliveryManagerRoutes'
export { delivery } from './deliveryRoutes'
export { driver } from './driverRoutes'